In [1]:
import pandas as pd
import numpy as np

d1= np.array([1,2,3,4])

print(d1)

print(d1.ndim)
print(d1.shape)

[1 2 3 4]
1
(4,)


In [2]:
d2= np.array([[1,2,3],[4,5,6],
            [7,8,9],[10,11,12]])

print(d2)
print(d1.ndim)
print(d1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1
(4,)


In [3]:
d3= np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]],
             [[13,14,15],[16,17,18]]])

print(d3)
print(d1.ndim)
print(d1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
(4,)


In [4]:

np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
np.random.randint(1, 21, size=(3, 3))

array([[17, 13, 11],
       [ 4, 18, 13],
       [ 9,  9, 11]])

In [6]:
second_row = d2[1]
print("Second row:", second_row)

column1 = d2[:, 0]
print("First column:", column1)

subarray = d2[0:2, 1:3]
print("Subarray (rows 1–2, columns 2–4):", subarray)

# Ensure arr is defined
arr = np.arange(1, 13)

arr_replaced = arr.copy()
arr_replaced[arr_replaced % 2 == 0] = -1
print("arr with even numbers replaced by -1:", arr_replaced)

Second row: [4 5 6]
First column: [ 1  4  7 10]
Subarray (rows 1–2, columns 2–4): [[2 3]
 [5 6]]
arr with even numbers replaced by -1: [ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1]


In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print("sum=", np.add(a, b),
	  "subtraction=", np.subtract(a, b),
	  "multiplication=", np.multiply(a, b),
	  "division=", np.divide(a, b))

sum= [5 7 9] subtraction= [-3 -3 -3] multiplication= [ 4 10 18] division= [0.25 0.4  0.5 ]


In [8]:

arr=np.arange(1,13)
arr
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])